server:
  port: 80
  servlet:
    encoding:
      charset: UTF-8
      force: true
    session:
      timeout: 10m
spring:
  session:
    redis:
      namespace: spring:session
    store-type: redis
  data:
    redis:
      host: localhost
      port: 6379
      password: qqqqq
  mvc:
    view:
      prefix: /views/
      suffix: .jsp
  datasource:
#    driver-class-name:  net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#    url: jdbc:log4jdbc:mysql://127.0.0.1:3306/shopdb?characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://database-1.cpqe6sioasnt.ap-northeast-2.rds.amazonaws.com/testdb
    #user01/111111
    username: test
    password: 111111
mybatis:
  type-aliases-package: com.hana.app.data.dto
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    root: info

app:
  url:
    serverurl: http://172.16.21.91:81
    chatboturl: http://172.16.21.91
  dir:
#    imgdir: file:///C:/project/imgs/  # 화면 출력 용
#    uploadimgdir: C:/project/imgs/    # 파일 Write 용
#    logdir: file:///C:/project/logs/
    imgdir: file:/root/imgs/ # 화면 출력 용
    uploadimgdir: /root/imgs/    # 파일 Write 용
    logdir: file:/root/logs/
  key:
    wkey: ENC(4b2QhZtHxU+VJF4KGgEFamJCW3LkcuQjwrNldg9+kdreoQDYoS/DTlLQstIc637fAoMEwCpIVyiAbDP0/7TI3YpCNKcr+zLqKH7oNCHzF5K+B6ETHW1gWzeKIqdUNCk5dWRDOer9knDq/cd6lBE7Hw==)
    whkey: ENC(HE6zJ0DpDGhlGZSvdc1aN++IWaW5YHRz6qdK3xPBPtUJU/vJUQEnExcV8MnXJ7um)
    ncp-id: ENC(KSrjJJfkLujcxeEposGXJlKKyb5k9C49)
    ncp-secret: ENC(Pl9mdJu/zld0bwZqSTGlqZpS9Dbw/ae+VHx5FMyU/PiT+a7kwZe8lWq9nt+5ezPYKbK/NQCqOzc=)
    chatbot_url: ENC(ZnHGJ0YJ2g3MTdDhMVCDuKc7oz4HfcgMTSOymi8xKMRVeuz5OOTUqBY34fD5g8UvSq0Cdh4Teg4THsI3U1Dx1bfUEmherz18Uqd0VBAmQ+qC66sI1GdDlhV0hDzezd8cMZ+oon8YZ/CtL0+IJqdlA9QlesmKABHQhxiF3M595Hk=)
    chatbot_key: ENC(6t6htbGHY74v6i5Yt0dyZs2wqv5RLhgE9WWhGN53k3j2M2q9LMQseb4hweMq04vVux4yU8649V0=)
    kakao_rest_key: ENC(RnDbPagfIlw2xJ3Zm0yeK4QxY6OFKZuUvizDIMbiBh9GCSBpGFlfyAmABWokCRPZ)
    #    file:/root/users/project/imgs/

